### ISSUE TITLE
DOC: docs not compiling on readthedocs for main

### ISSUE THREAD

**Issue by jklenzing** [sami2py/sami2py#121]
**Describe the bug**
Latest build on main is not compiling.  From error log:
```
Running Sphinx v1.8.5
ERROR:root:problem importing sami2py: No module named 'numpy'
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sami2py/checkouts/main/sami2py/__init__.py", line 65, in <module>
    from sami2py import _core, _core_class, utils  # noqa: F401
  File "/home/docs/checkouts/readthedocs.org/user_builds/sami2py/checkouts/main/sami2py/_core.py", line 34, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
numpy is definitely in the setup.cfg as a requirement.  Not sure why this is broken.

**Comment by jklenzing** [comment]
Closing with merge of #123
